### ISSUE TITLE
Error on invalid query should be more explicit

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-client-js#112]
## Summary

Calling cozy.client.data.query with invalid parameters should return an explicit error message

## STR
```
cozy.client.data.query(myIndex, {}).then().catch((err) => { console.error(err);})
```

## Expected result

The full error returned by the server: `{"error":"missing_required_key","ok":false,"reason":"Missing required key: selector","status":"400"}`

## Actual result

Only an Error object, without name nor message.

## Version of CozyClientJs

0.1.7

**Comment by sebn** [comment]
I believe the error name was already fixed. Last commit added the missing details.

@clochix feel free to reopen / ping me in case it doesn't work as expected.
