### ISSUE TITLE
Default content-type depending on extension

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client-js#197]
In application code (ACH), I see : 

```js
  switch (fileJSON.extension) {
    case '.jpg':
    case '.jpeg':
    case '.gif':
    case '.png':
    case '.tiff':
      contentType = `image/${fileJSON.extension.substring(1)}`
      break
    case '.pdf':
      contentType = `application/pdf`
      break
    default:
      contentType = ''
      break
  }
...
client.files.create(
```

I think it should be the responsibility of `client.files.create` to do that.

**Comment by nono** [comment]
I don't think it's the right way to do that. Browsers fill automatically the content-type when uploading a file. For nodejs stuff (like ACH), we can rely on packages like [`mime`](https://www.npmjs.com/package/mime).

**Comment by ptbrowne** [comment]
Yes I think we should rely on `mime` to do that. But still I think it should be the responsibility of cozy-client-js to do that.
