### ISSUE TITLE
Check if we need babel-polyfill

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client-js#221]
Following https://github.com/cozy/cozy-bar/pull/113 where we had a problem importing twice babel-polyfill in the context of an app (1st via cozy-client, 2nd via cozy-bar), we removed `babel-polyfill` from the cozy-bar. Do we need to do the same in cozy-client ? Would it be better to import polyfills via babel-preset-env (in our case via babel-preset-cozy-app) ?

I post this issue here so I do not forget, this is not an immediate bug. ping @CPatchane

**Comment by gregorylegarec** [comment]
As long as cozy-client-js is still usable in a "simple" vanilla app without any dependency, we may remove it.

**Comment by enguerran** [comment]
Minute of meeting (@enguerran et @ptbrowne) :

- y'a un bon mois, patrick a repéré un bug sur safari et à remonter la source jusqu'à un int8array, ce qui lui a fait penser à un souci de polyfill
- suspectant que charger 2 fois `babel-polyfill` pouvait amener à des bugs, il a viré [`babel-polyfill`](https://babeljs.io/docs/usage/polyfill) et a plus ou moins cargo culté l'ajout d'un [`transform-runtime`](http://babeljs.io/docs/plugins/transform-runtime) dans https://github.com/cozy/cozy-bar/pull/113 via https://github.com/CPatchane/create-cozy-app/blob/master/packages/babel-preset-cozy-app/index.js
- sans trop chercher plus de détails, il a alerté via une [issue sur cozy-client-js](https://github.com/cozy/cozy-client-js/issues/221) que je n'avais pas vu
- sans trop chercher plus de détails, je m'en vais virer `babel-polyfill` de la lib car `babel-polyfill` est déjà chargée par `cozy-drive`
- ce qui est différent entre `cozy-client-js` servie par la stack ou inclue dans les imports de `cozy-drive`, c'est que dans le 2e cas, on passe par une [`babel-loader`](https://github.com/babel/babel-loader) qui doit faire des trucs pour pas que ça pète.
- si aucun `polyfill` n'est présent lors du runtime, la console log `regeneratorRuntime is not defined`, par ailleurs :
    - si on ajoute `babel-polyfill` dans cozy-drive, c'est ok
    - si on ajoute `babel-polyfill` dans cozy-client-js, c'est ok
    - si on ajoute aux 2 endroits, c'est ko (si les scripts sont chargés indépendamment)
