### ISSUE TITLE
Authentification fails on iOS9

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client-js#235]
URLSearchParams does not have `.has` method on iOS9.

Makes authentication fail at https://github.com/cozy/cozy-client-js/blob/b12fb52da002742c83bfc87632a3bc6440d1a8c0/src/index.js#L224

<img width=50% src=https://user-images.githubusercontent.com/465582/33443019-cddfd3a0-d5f6-11e7-8f55-e714533d46f3.png />

Investigating if we should polyfill for iOS9 via babel-preset-env.

CanIUse for URL APIs URLSearchParams : https://caniuse.com/#search=URL

![image](https://user-images.githubusercontent.com/465582/33443163-2e97ec14-d5f7-11e7-9269-ccaa5407ad1b.png)

**Comment by nono** [comment]
If `url.searchParams` is not well supported, it's also possible to use `url.search` to avoid the polyfill game. IIRC, `url.search` is a string, not an object, so it's a bit more work but it's used only at very specific places, so it's not a big deal.

**Comment by ptbrowne** [comment]
OK I think it is a good solution first ✅, but I think we need to decide what is the lowest version of mobile browsers that we support. It is not yet specified in the .babelrc.

**Comment by ptbrowne** [comment]
URL API and URLSearchParams are not polyfilled anyway : https://github.com/zloirock/core-js/issues/117
