### ISSUE TITLE
Not possible to do multiple delete

### ISSUE THREAD

**Issue by doubleface** [cozy/cozy-client-js#58]
The databrowser application needs to be able to delete all the documents associated to a given doctype (to be compliant with the previous version).

I do not see (in the docs and in the code) any possibility to do that, even multiple deletion actually.
Is it forcasted to implement this or should I implement a chain of promises which deletes all the items one by one (which is not very satisfying) ?

Am I missing something ?

**Comment by goldoraf** [comment]
@doubleface If you still have this need, feel free to reopen or PR ;)
