### ISSUE TITLE
No simple way to get all the documents for a given doctype

### ISSUE THREAD

**Issue by doubleface** [cozy/cozy-client-js#59]
After reviewing the doc and the code, the only way I found to get all the document for a given doctype is : 

```javascript
cozy.defineIndex("doctype", ["_id"])
.then(index => cozy.query(index, {
    selector: {
        "_id": {
          "$gt": 0
          }
        }
    }
));
```

since all docs have an id.
Please tell me there is a better way...

**Comment by nono** [comment]
We have a route `GET /data/:doctype/_all_docs` on the cozy-stack. I don't know if there is a function in cozy-client-js to use it. But, if it is not the case, it should be easy to add it.

**Comment by clochix** [comment]
We add [such a method in cozydb](https://cozy.github.io/cozy-db/doc/classes/Model.html#all-class).

Also, a `first` method could be useful, for content type with only a single document (nice but not required).

**Comment by goldoraf** [comment]
Fixed by https://github.com/cozy/cozy-client-js/pull/202 that will be merged shortly
