### ISSUE TITLE
No way to get the list of doctypes

### ISSUE THREAD

**Issue by doubleface** [cozy/cozy-client-js#60]
V2 allows that. I have heard this is more complicated for the V3 at the moment an it is needed by the databrowser. It even needs to get the number of documents for each doctype.

I have a workaround for V2, but obviously, not compatible with v3.
Can you do something about that?

**Comment by nono** [comment]
We have a route `GET /data/:doctype/_all_docs` on the cozy-stack. I don't know if there is a function in cozy-client-js to use it. But, if it is not the case, it should be easy to add it.

**Comment by doubleface** [comment]
And for the number of documents for each doctype. In V2, it is possible to get it with one request, but I still can get it asynchroneously one by one if no better solution exists.

**Comment by doubleface** [comment]
I did not read it carefully, this seems to be the answer for #59 . What is needed here is the list of all the doctypes.

**Comment by nono** [comment]
It is work in progress: https://github.com/cozy/cozy-stack/pull/279

**Comment by goldoraf** [comment]
@doubleface do you still have this need? Feel free to reopen the issue if necessary.
